### ISSUE TITLE
Will there be a new version that supports Java 8

### ISSUE THREAD

**Issue by 4ra1n** [Vineflower/vineflower#222]
Hello all,

Recently, I was developing a project based on QuiltFlower, but because of some requirements, I had to use Java 8 to do it, so I was forced to downgrade to version 1.8.1 of QuiiltFlower. Will you provide a version that can run on Java 8 in the future?

Kind Regards

**Comment by SuperCoder7979** [comment]
Hey- At this moment, a new version that supports Java 8 isn't planned. This is mainly due to us using new Java 11 APIs in QF 1.9, as well as potentially using parts of the module system for the upcoming plugins feature in 1.10.

With that being said, I am working on a personal project that will allow you to translate Java 11 jars to Java 8. If that releases, that may fix your issues- I'll leave an update here if that occurs. Your best bet is probably to use 1.8.1 for now.

**Comment by jaskarth** [comment]
Support for Java 8 is not planned, closing.
