### ISSUE TITLE
The decompiler configuration options are not working 

### ISSUE THREAD

**Issue by meiMingle** [Vineflower/vineflower#406]
## Vineflower version
1.10.1

## Describe the bug
At least `Dump Code Lines` does not work at the moment.

## Additional information
See [Recaf/issues/801](https://github.com/Col-E/Recaf/issues/801)

**Comment by Geolykt** [comment]
This is a bug in recaf - it works just fine in gslStarplane.

**Comment by Geolykt** [comment]
Okay, I've just did some further digging into this issue since "works on my end" would've seriously angered me.
The `Dump Code Lines` attribute is mostly completely irrelevant to most users - it just has the effect that the line mappings are stored in the output jar.

What you are looking for is `DUMP_ORIGINAL_LINES` (or `__dump_original_lines__`). However recaf does not expose this option - probably because the name hints at this attribute probably being for internal use only.

**Comment by Col-E** [comment]
> However recaf does not expose this option

I just went down the list in `IFernflowerPreferences` but if I missed something, that's my bad. I agree that if the DCL flag is for zip output I should hide it so people don't get confused.

This issue can be closed.
